from typing import Any, Protocol


class ICommand(Protocol):
    def set_next(self, command: "ICommand") -> "ICommand": ...
    def set_previous(self, command: "ICommand") -> "ICommand": ...
    def execute(self) -> Any: ...
    def undo(self) -> Any: ...
